version: '3.8'

services:
  react-app:
    image: node:23-alpine # Use Node.js Alpine image for lightweight builds
    container_name: tech-image-gallery
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4111:4111" # Map port 4111
    command: sh -c "npm install && npm run build && npx serve -s dist -l 4111"